import * as actions from '@controleonline/ui-default/src/store/default/actions';
import * as getters from '@controleonline/ui-default/src/store/default/getters';
import mutations from '@controleonline/ui-default/src/store/default/mutations';
import {CTE_FISCAL_COLUMNS} from '@controleonline/ui-logistic/src/shared/ctePendingInvoices';

export default {
  namespaced: true,
  state: {
    item: null,
    items: [],
    resourceEndpoint: 'invoice_taxes',
    isLoading: false,
    error: '',
    totalItems: 0,
    summary: {},
    filters: {},
    reload: false,
    add: false,
    configs: {
      import: {
        enabled: true,
        importType: 'invoice_tax',
        allowedExtensions: ['xml', 'zip'],
      },
    },
    columns: [
      {name: 'id', label: 'ID', isIdentity: true, editable: false, externalFilter: true},
      ...CTE_FISCAL_COLUMNS,
      {
        name: 'company',
        label: 'Empresa',
        editable: false,
        externalFilter: true,
        list: 'people',
        searchParam: 'company',
        format: value => (value?.name || value?.alias || value?.['@id'] || '-'),
        formatList: value => (value && value['@id'] ? {value: value['@id'].split('/').pop(), label: `${value.name || ''} - ${value.alias || ''}`.trim() || value['@id']} : value),
        saveFormat: value => (value ? `/people/${value.value || value}` : null),
      },
      {
        name: 'client',
        label: 'Destinatário',
        editable: false,
        externalFilter: true,
        list: 'people',
        searchParam: 'client',
        format: value => (value?.name || value?.alias || value?.['@id'] || '-'),
        formatList: value => (value && value['@id'] ? {value: value['@id'].split('/').pop(), label: `${value.name || ''} - ${value.alias || ''}`.trim() || value['@id']} : value),
        saveFormat: value => (value ? `/people/${value.value || value}` : null),
      },
      {
        name: 'provider',
        label: 'Remetente',
        editable: false,
        externalFilter: true,
        list: 'people',
        searchParam: 'provider',
        format: value => (value?.name || value?.alias || value?.['@id'] || '-'),
        formatList: value => (value && value['@id'] ? {value: value['@id'].split('/').pop(), label: `${value.name || ''} - ${value.alias || ''}`.trim() || value['@id']} : value),
        saveFormat: value => (value ? `/people/${value.value || value}` : null),
      },
      {
        name: 'carrier',
        label: 'Transportadora',
        editable: false,
        externalFilter: true,
        list: 'people',
        searchParam: 'carrier',
        format: value => (value?.name || value?.alias || value?.['@id'] || '-'),
        formatList: value => (value && value['@id'] ? {value: value['@id'].split('/').pop(), label: `${value.name || ''} - ${value.alias || ''}`.trim() || value['@id']} : value),
        saveFormat: value => (value ? `/people/${value.value || value}` : null),
      },
      {name: 'invoiceTotal', label: 'Total', type: 'money', summary: 'sum', editable: false, align: 'right', externalFilter: true},
      {
        name: 'status',
        label: 'Status',
        editable: false,
        externalFilter: true,
        list: 'status/getItems',
        listRequestParams: {context: 'invoice_tax'},
        searchParam: 'status',
        format: value => (value?.status || value?.realStatus || '-'),
        formatList: value => (value && value['@id'] ? {value: value['@id'].split('/').pop(), label: value.status || value.realStatus || value['@id']} : value),
        saveFormat: value => (value ? `/statuses/${value.value || value}` : null),
      },
    ],
  },
  actions,
  getters,
  mutations,
};
