import {StyleSheet} from 'react-native';

const createStyles = palette =>
  StyleSheet.create({
    pageRoot: {
      flex: 1,
      backgroundColor: palette?.pageBg,
    },
    pageScroll: {
      flex: 1,
    },
    pageScrollContent: {
      paddingHorizontal: 10,
      paddingTop: 10,
      gap: 10,
    },
    topBarWrap: {
      gap: 10,
    },
    sectionCard: {
      borderRadius: 16,
      borderWidth: 1,
      borderColor: palette?.borderSoft,
      backgroundColor: palette?.cardBg,
      padding: 12,
      gap: 8,
    },
    sectionHeaderRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 10,
    },
    sectionHeaderText: {
      flex: 1,
      gap: 2,
    },
    sectionHeaderAction: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    sectionHeaderRightGroup: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    sectionTitle: {
      color: palette?.textPrimary,
      fontSize: 14,
      fontWeight: '900',
    },
    sectionSubtitle: {
      color: palette?.textSecondary,
      fontSize: 11,
      fontWeight: '700',
      lineHeight: 14,
    },
    sectionBody: {
      gap: 8,
    },
    sectionActionRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    deliveryHeroHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 12,
    },
    deliveryHeroHeaderText: {
      flex: 1,
      gap: 2,
    },
    deliveryHeroLabel: {
      color: palette?.accentInfo,
      fontSize: 10,
      fontWeight: '900',
      textTransform: 'uppercase',
      letterSpacing: 0.2,
    },
    deliveryHeroValue: {
      color: palette?.textPrimary,
      fontSize: 15,
      fontWeight: '900',
      lineHeight: 19,
    },
    deliveryHeroMeta: {
      color: palette?.textSecondary,
      fontSize: 11,
      fontWeight: '700',
      lineHeight: 14,
    },
    deliveryHeroMetaRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
    },
    routeSummaryStrip: {
      flexDirection: 'row',
      alignItems: 'stretch',
      gap: 8,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: palette?.borderSoft,
      backgroundColor: palette?.cardBgSoft,
      padding: 10,
    },
    routeSummaryStop: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      borderRadius: 12,
      paddingVertical: 2,
    },
    routeSummaryStopSuccess: {
      backgroundColor: 'transparent',
    },
    routeSummaryIconWrap: {
      width: 30,
      height: 30,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: palette?.borderSoft,
      backgroundColor: '#FFFFFF',
      alignItems: 'center',
      justifyContent: 'center',
    },
    routeSummaryIconWrapSuccess: {
      borderColor: '#86EFAC',
      backgroundColor: '#F0FDF4',
    },
    routeSummaryTextWrap: {
      flex: 1,
      gap: 1,
    },
    routeSummaryLabel: {
      color: palette?.accentInfo,
      fontSize: 9,
      fontWeight: '900',
      textTransform: 'uppercase',
      letterSpacing: 0.2,
    },
    routeSummaryPrimary: {
      color: palette?.textPrimary,
      fontSize: 12,
      fontWeight: '900',
      lineHeight: 15,
    },
    routeSummarySecondary: {
      color: palette?.textSecondary,
      fontSize: 10,
      fontWeight: '700',
      lineHeight: 12,
    },
    routeSummaryDivider: {
      width: 28,
      alignItems: 'center',
      justifyContent: 'center',
    },
    modalSheetRoot: {
      flex: 1,
      justifyContent: 'flex-end',
      backgroundColor: 'rgba(15, 23, 42, 0.45)',
      paddingTop: 24,
    },
    modalSheetBackdrop: {
      flex: 1,
    },
    modalSheetWrap: {
      width: '100%',
      maxHeight: '92%',
      justifyContent: 'flex-end',
    },
    assignmentModalCard: {
      width: '100%',
      maxHeight: '92%',
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      borderWidth: 1,
      borderColor: palette?.borderSoft,
      backgroundColor: palette?.cardBg,
      paddingHorizontal: 14,
      paddingTop: 12,
      paddingBottom: 14,
    },
    deliveryCodeHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
      marginBottom: 8,
    },
    deliveryCodeStepBadge: {
      alignSelf: 'flex-start',
      borderRadius: 999,
      borderWidth: 1,
      borderColor: palette?.borderSoft,
      backgroundColor: palette?.cardBgSoft,
      color: palette?.accentInfo,
      fontSize: 11,
      fontWeight: '800',
      paddingHorizontal: 10,
      paddingVertical: 5,
      textTransform: 'uppercase',
    },
    deliveryCodeCloseButton: {
      width: 34,
      height: 34,
      borderRadius: 17,
      borderWidth: 1,
      borderColor: palette?.borderSoft,
      backgroundColor: palette?.cardBgSoft,
      alignItems: 'center',
      justifyContent: 'center',
    },
    deliveryCodeModalTitle: {
      color: palette?.textPrimary,
      fontSize: 20,
      fontWeight: '900',
      marginBottom: 10,
    },
    deliveryCodeScroll: {
      flex: 1,
    },
    deliveryCodeScrollContent: {
      paddingBottom: 8,
      gap: 8,
    },
    assignmentSearchBox: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: palette?.borderSoft,
      backgroundColor: palette?.cardBgSoft,
      paddingHorizontal: 12,
      minHeight: 46,
    },
    assignmentSearchInput: {
      flex: 1,
      color: palette?.textPrimary,
      fontSize: 14,
      paddingVertical: 0,
    },
    assignmentEmptyState: {
      borderRadius: 14,
      borderWidth: 1,
      borderStyle: 'dashed',
      borderColor: palette?.borderSoft,
      backgroundColor: palette?.cardBgSoft,
      paddingHorizontal: 12,
      paddingVertical: 12,
      gap: 6,
    },
    assignmentEmptyStateTitle: {
      color: palette?.textPrimary,
      fontSize: 13,
      fontWeight: '900',
    },
    assignmentEmptyStateText: {
      color: palette?.textSecondary,
      fontSize: 11,
      fontWeight: '600',
      lineHeight: 14,
    },
    assignmentOptionCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: palette?.borderSoft,
      backgroundColor: palette?.cardBgSoft,
      paddingHorizontal: 12,
      paddingVertical: 11,
    },
    assignmentOptionCardSelected: {
      borderColor: palette?.accentInfo,
      backgroundColor: '#EFF8FF',
    },
    assignmentOptionTextWrap: {
      flex: 1,
      gap: 2,
    },
    assignmentOptionTitle: {
      color: palette?.textPrimary,
      fontSize: 13,
      fontWeight: '900',
    },
    assignmentOptionMeta: {
      color: palette?.textSecondary,
      fontSize: 11,
      fontWeight: '600',
      lineHeight: 14,
    },
    assignmentOptionBadge: {
      color: palette?.accentInfo,
      fontSize: 11,
      fontWeight: '900',
      textTransform: 'uppercase',
      letterSpacing: 0.2,
    },
    assignmentQuickActionCard: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: palette?.accentInfo,
      backgroundColor: palette?.cardBg,
      paddingHorizontal: 12,
      paddingVertical: 12,
    },
    assignmentQuickActionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    assignmentQuickActionTitle: {
      color: palette?.accentInfo,
      fontSize: 12,
      fontWeight: '900',
      textTransform: 'uppercase',
      letterSpacing: 0.2,
    },
    assignmentFormInput: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: palette?.borderSoft,
      backgroundColor: palette?.cardBgSoft,
      color: palette?.textPrimary,
      minHeight: 46,
      paddingHorizontal: 12,
      fontSize: 14,
      fontWeight: '600',
    },
    assignmentFormHalf: {
      flex: 1,
    },
    assignmentFormRow: {
      flexDirection: 'row',
      gap: 8,
    },
    assignmentContextCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: palette?.borderSoft,
      backgroundColor: palette?.cardBgSoft,
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    assignmentContextText: {
      flex: 1,
      color: palette?.textPrimary,
      fontSize: 12,
      fontWeight: '700',
      lineHeight: 18,
    },
    sectionField: {
      flexGrow: 1,
      flexBasis: 150,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: palette?.borderSoft,
      backgroundColor: palette?.cardBgSoft,
      padding: 10,
      gap: 3,
    },
    sectionLabel: {
      color: palette?.accentInfo,
      fontSize: 10,
      fontWeight: '900',
      textTransform: 'uppercase',
      letterSpacing: 0.15,
    },
    sectionValue: {
      color: palette?.textPrimary,
      fontSize: 12,
      fontWeight: '800',
      lineHeight: 15,
    },
    statusPill: {
      alignSelf: 'flex-start',
      borderRadius: 999,
      borderWidth: 1,
      borderColor: palette?.accentInfo,
      backgroundColor: palette?.cardBgSoft,
      paddingHorizontal: 10,
      paddingVertical: 4,
    },
    statusPillMuted: {
      borderColor: palette?.borderSoft,
      backgroundColor: '#F8FAFC',
    },
    statusPillWarning: {
      borderColor: '#F59E0B',
      backgroundColor: '#FFFBEB',
    },
    statusPillSuccess: {
      borderColor: '#16A34A',
      backgroundColor: '#F0FDF4',
    },
    statusPillDanger: {
      borderColor: '#c10015',
      backgroundColor: '#FEF2F2',
    },
    statusPillText: {
      color: palette?.accentInfo,
      fontSize: 11,
      fontWeight: '900',
      letterSpacing: 0.2,
      textTransform: 'uppercase',
    },
    statusPillTextMuted: {
      color: palette?.textSecondary,
    },
    statusPillTextWarning: {
      color: '#D97706',
    },
    statusPillTextSuccess: {
      color: '#16A34A',
    },
    statusPillTextDanger: {
      color: '#c10015',
    },
    actionButton: {
      minHeight: 36,
      paddingHorizontal: 12,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      gap: 6,
      borderWidth: 1,
      borderColor: palette?.borderSoft,
      backgroundColor: palette?.cardBg,
    },
    actionButtonPrimary: {
      backgroundColor: palette?.accentInfo,
      borderColor: palette?.accentInfo,
    },
    actionButtonSecondary: {
      backgroundColor: palette?.cardBgSoft,
    },
    actionButtonSuccess: {
      backgroundColor: '#16A34A',
      borderColor: '#16A34A',
    },
    actionButtonDanger: {
      backgroundColor: '#FEF2F2',
      borderColor: '#FCA5A5',
    },
    actionButtonDisabled: {
      opacity: 0.55,
    },
    actionButtonText: {
      color: palette?.textPrimary,
      fontSize: 11,
      fontWeight: '900',
      textTransform: 'uppercase',
      letterSpacing: 0.2,
    },
    actionButtonTextPrimary: {
      color: '#FFFFFF',
    },
    actionButtonTextSecondary: {
      color: palette?.accentInfo,
    },
    actionButtonTextSuccess: {
      color: '#FFFFFF',
    },
    actionButtonTextDanger: {
      color: '#B91C1C',
    },
    deliveryAcceptanceCard: {
      borderRadius: 16,
      borderWidth: 1,
      borderColor: '#86EFAC',
      backgroundColor: '#F0FDF4',
      padding: 12,
      gap: 10,
    },
    deliveryAcceptanceTextWrap: {
      gap: 3,
    },
    deliveryAcceptanceTitle: {
      color: '#166534',
      fontSize: 14,
      fontWeight: '900',
      textTransform: 'uppercase',
      letterSpacing: 0.2,
    },
    deliveryAcceptanceSubtitle: {
      color: '#15803D',
      fontSize: 11,
      fontWeight: '700',
      lineHeight: 14,
    },
    deliveryAcceptanceActions: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    deliveryAcceptanceButton: {
      flexGrow: 1,
      flexBasis: 140,
    },
    routeGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    mapViewportWrap: {
      width: '100%',
      height: 320,
      borderRadius: 14,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: palette?.borderSoft,
      backgroundColor: '#E5EEF5',
    },
    quoteGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    quoteCard: {
      flexGrow: 1,
      flexBasis: 250,
      minWidth: 220,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: palette?.borderSoft,
      backgroundColor: palette?.cardBgSoft,
      padding: 12,
      gap: 8,
      shadowColor: '#0F172A',
      shadowOpacity: 0.03,
      shadowRadius: 8,
      shadowOffset: {width: 0, height: 3},
      elevation: 1,
    },
    quoteCardSelected: {
      borderColor: palette?.accentInfo,
      backgroundColor: '#EFF8FF',
    },
    quoteCardUnavailable: {
      opacity: 0.92,
      backgroundColor: '#F8FAFC',
    },
    quoteCardHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      gap: 10,
    },
    quoteCardTitleWrap: {
      flex: 1,
      gap: 4,
    },
    quoteBrandRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    quoteBrandTextWrap: {
      flex: 1,
      gap: 2,
    },
    quoteCardTitle: {
      color: palette?.textPrimary,
      fontSize: 14,
      fontWeight: '900',
    },
    quoteCardMeta: {
      color: palette?.textSecondary,
      fontSize: 10,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.15,
    },
    quoteCardBody: {
      gap: 6,
    },
    quoteInfoRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
    },
    providerBadge: {
      width: 28,
      height: 28,
      borderRadius: 9,
      borderWidth: 1,
      borderColor: palette?.borderSoft,
      backgroundColor: '#FFFFFF',
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
    },
    providerBadgeImage: {
      width: 20,
      height: 20,
    },
    providerBadgeText: {
      color: palette?.accentInfo,
      fontSize: 10,
      fontWeight: '900',
      letterSpacing: 0.1,
    },
    compactChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: palette?.borderSoft,
      backgroundColor: '#FFFFFF',
      paddingHorizontal: 8,
      paddingVertical: 4,
    },
    compactChipSuccess: {
      borderColor: '#86EFAC',
      backgroundColor: '#F0FDF4',
    },
    compactChipDanger: {
      borderColor: '#FCA5A5',
      backgroundColor: '#FEF2F2',
    },
    compactChipMuted: {
      borderColor: palette?.borderSoft,
      backgroundColor: '#F8FAFC',
    },
    compactChipWarning: {
      borderColor: '#FDE68A',
      backgroundColor: '#FFFBEB',
    },
    compactChipText: {
      color: palette?.textPrimary,
      fontSize: 10,
      fontWeight: '800',
      lineHeight: 12,
    },
    compactChipTextWarning: {
      color: '#D97706',
    },
    compactChipTextSuccess: {
      color: '#166534',
    },
    compactChipTextDanger: {
      color: '#B91C1C',
    },
    compactChipTextMuted: {
      color: palette?.textSecondary,
    },
    quoteSummary: {
      color: palette?.accentInfo,
      fontSize: 11,
      fontWeight: '800',
      textTransform: 'uppercase',
      letterSpacing: 0.15,
    },
    quoteMessage: {
      color: palette?.textSecondary,
      fontSize: 10,
      fontWeight: '600',
      lineHeight: 13,
    },
    quoteFooter: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    emptyState: {
      borderRadius: 14,
      borderWidth: 1,
      borderStyle: 'dashed',
      borderColor: palette?.borderSoft,
      backgroundColor: palette?.cardBg,
      padding: 12,
      gap: 6,
    },
    emptyStateTitle: {
      color: palette?.textPrimary,
      fontSize: 12,
      fontWeight: '900',
    },
    emptyStateText: {
      color: palette?.textSecondary,
      fontSize: 11,
      fontWeight: '600',
      lineHeight: 14,
    },
    loadingWrap: {
      minHeight: 120,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 24,
    },
    errorBanner: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: '#FECACA',
      backgroundColor: '#FEF2F2',
      padding: 10,
    },
    errorText: {
      color: '#B91C1C',
      fontSize: 12,
      fontWeight: '700',
      lineHeight: 16,
    },
    // Icon colors
    iconColorPrimary: {
      color: palette?.accentInfo,
    },
    iconColorWhite: {
      color: '#FFFFFF',
    },
    iconColorSecondary: {
      color: palette?.textSecondary,
    },
    iconColorMuted: {
      color: palette?.textSecondary,
    },
    iconColorWarning: {
      color: '#D97706',
    },
    iconColorSuccess: {
      color: '#16A34A',
    },
    iconColorDanger: {
      color: '#DC2626',
    },
  });

export default createStyles;
