import {StyleSheet} from 'react-native';

const createStyles = palette =>
  StyleSheet.create({
    pageRoot: {
      flex: 1,
      backgroundColor: palette?.pageBg || '#F8FAFC',
    },
    pageScrollContent: {
      paddingHorizontal: 10,
      paddingTop: 10,
      paddingBottom: 24,
      gap: 8,
    },
    topBarWrap: {
      gap: 8,
    },
    heroCard: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: palette?.borderSoft || '#D6E4F0',
      backgroundColor: palette?.cardBg || '#FFFFFF',
      padding: 12,
      gap: 8,
      shadowColor: '#0F172A',
      shadowOpacity: 0.04,
      shadowRadius: 10,
      shadowOffset: {width: 0, height: 4},
      elevation: 1,
    },
    heroHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    heroTextWrap: {
      flex: 1,
      gap: 4,
    },
    heroTitle: {
      color: palette?.textPrimary || '#0F172A',
      fontSize: 16,
      fontWeight: '900',
    },
    heroSubtitle: {
      color: palette?.textSecondary || '#475569',
      fontSize: 11,
      fontWeight: '700',
      lineHeight: 14,
    },
    statusPill: {
      alignSelf: 'flex-start',
      borderRadius: 999,
      borderWidth: 1,
      borderColor: palette?.accentInfo || '#0284C7',
      backgroundColor: palette?.cardBgSoft || '#EFF8FF',
      paddingHorizontal: 10,
      paddingVertical: 4,
    },
    statusPillText: {
      color: palette?.accentInfo || '#0284C7',
      fontSize: 11,
      fontWeight: '900',
      letterSpacing: 0.2,
      textTransform: 'uppercase',
    },
    bodyStack: {
      gap: 8,
    },
    sectionCard: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: palette?.borderSoft || '#D6E4F0',
      backgroundColor: palette?.cardBg || '#FFFFFF',
      padding: 12,
      gap: 8,
    },
    sectionHeader: {
      gap: 2,
    },
    sectionTitle: {
      color: palette?.textPrimary || '#0F172A',
      fontSize: 14,
      fontWeight: '900',
    },
    sectionSubtitle: {
      color: palette?.textSecondary || '#64748B',
      fontSize: 11,
      fontWeight: '700',
      lineHeight: 14,
    },
    sectionBody: {
      gap: 8,
    },
    sectionRow: {
      gap: 4,
    },
    sectionRowSplit: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    summaryGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    routeGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    selectionGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    selectionPanel: {
      flexGrow: 1,
      flexBasis: 280,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: palette?.borderSoft || '#D6E4F0',
      backgroundColor: palette?.cardBgSoft || '#F8FBFF',
      padding: 10,
      gap: 8,
    },
    selectionPanelHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 8,
    },
    selectionPanelTitleWrap: {
      flex: 1,
      gap: 2,
    },
    selectionPanelTitle: {
      color: palette?.textPrimary || '#0F172A',
      fontSize: 13,
      fontWeight: '900',
    },
    selectionPanelSubtitle: {
      color: palette?.textSecondary || '#64748B',
      fontSize: 11,
      fontWeight: '700',
      lineHeight: 14,
    },
    compactList: {
      gap: 8,
    },
    sectionField: {
      flexGrow: 1,
      flexBasis: 150,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: palette?.borderSoft || '#D6E4F0',
      backgroundColor: palette?.cardBgSoft || '#F8FBFF',
      padding: 10,
      gap: 3,
    },
    sectionLabel: {
      color: palette?.accentInfo || '#0284C7',
      fontSize: 10,
      fontWeight: '900',
      textTransform: 'uppercase',
      letterSpacing: 0.15,
    },
    sectionValue: {
      color: palette?.textPrimary || '#0F172A',
      fontSize: 12,
      fontWeight: '800',
      lineHeight: 15,
    },
    sectionHint: {
      color: palette?.textSecondary || '#64748B',
      fontSize: 11,
      fontWeight: '600',
      lineHeight: 14,
    },
    actionButton: {
      minHeight: 36,
      paddingHorizontal: 12,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      gap: 6,
      borderWidth: 1,
      borderColor: palette?.borderSoft || '#D6E4F0',
      backgroundColor: palette?.cardBg || '#FFFFFF',
    },
    actionButtonPrimary: {
      backgroundColor: palette?.accentInfo || '#0284C7',
      borderColor: palette?.accentInfo || '#0284C7',
    },
    actionButtonSecondary: {
      backgroundColor: palette?.cardBgSoft || '#F8FBFF',
    },
    actionButtonDisabled: {
      opacity: 0.55,
    },
    actionButtonText: {
      color: palette?.textPrimary || '#0F172A',
      fontSize: 11,
      fontWeight: '900',
      textTransform: 'uppercase',
      letterSpacing: 0.2,
    },
    actionButtonTextPrimary: {
      color: '#FFFFFF',
    },
    actionButtonTextSecondary: {
      color: palette?.accentInfo || '#0284C7',
    },
    sectionActionRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
    },
    courierCard: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: palette?.borderSoft || '#D6E4F0',
      backgroundColor: palette?.cardBgSoft || '#F8FBFF',
      padding: 10,
      gap: 8,
    },
    courierCardSelected: {
      borderColor: palette?.accentInfo || '#0284C7',
      backgroundColor: '#EFF8FF',
    },
    courierCardHeader: {
      gap: 4,
    },
    courierCardTitle: {
      color: palette?.textPrimary || '#0F172A',
      fontSize: 12,
      fontWeight: '900',
    },
    courierCardSubtitle: {
      color: palette?.textSecondary || '#64748B',
      fontSize: 11,
      fontWeight: '600',
      lineHeight: 14,
    },
    courierMetaRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
    },
    courierMetaPill: {
      borderRadius: 999,
      borderWidth: 1,
      borderColor: palette?.borderSoft || '#D6E4F0',
      backgroundColor: palette?.cardBg || '#FFFFFF',
      paddingHorizontal: 8,
      paddingVertical: 3,
    },
    courierMetaPillText: {
      color: palette?.textSecondary || '#475569',
      fontSize: 10,
      fontWeight: '800',
    },
    integrationCard: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: palette?.borderSoft || '#D6E4F0',
      backgroundColor: palette?.cardBgSoft || '#F8FBFF',
      padding: 10,
      gap: 8,
    },
    integrationCardActive: {
      borderColor: palette?.accentInfo || '#0284C7',
      backgroundColor: '#F0F9FF',
    },
    integrationHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      gap: 10,
    },
    integrationTitleWrap: {
      flex: 1,
      gap: 4,
    },
    integrationLabel: {
      color: palette?.textPrimary || '#0F172A',
      fontSize: 12,
      fontWeight: '900',
    },
    integrationMeta: {
      color: palette?.textSecondary || '#64748B',
      fontSize: 10,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.15,
    },
    integrationPrice: {
      color: palette?.textPrimary || '#0F172A',
      fontSize: 16,
      fontWeight: '900',
    },
    integrationEta: {
      color: palette?.textSecondary || '#64748B',
      fontSize: 11,
      fontWeight: '700',
    },
    integrationStatus: {
      color: palette?.accentInfo || '#0284C7',
      fontSize: 11,
      fontWeight: '900',
      textTransform: 'uppercase',
      letterSpacing: 0.15,
    },
    integrationBody: {
      gap: 4,
    },
    integrationFooter: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
    },
    emptyState: {
      borderRadius: 12,
      borderWidth: 1,
      borderStyle: 'dashed',
      borderColor: palette?.borderSoft || '#D6E4F0',
      backgroundColor: palette?.cardBg || '#FFFFFF',
      padding: 10,
      gap: 4,
    },
    emptyStateTitle: {
      color: palette?.textPrimary || '#0F172A',
      fontSize: 12,
      fontWeight: '900',
    },
    emptyStateText: {
      color: palette?.textSecondary || '#64748B',
      fontSize: 11,
      fontWeight: '600',
      lineHeight: 14,
    },
    linkButton: {
      alignSelf: 'flex-start',
      borderRadius: 999,
      borderWidth: 1,
      borderColor: palette?.accentInfo || '#0284C7',
      backgroundColor: '#EFF8FF',
      paddingHorizontal: 10,
      paddingVertical: 5,
    },
    linkButtonText: {
      color: palette?.accentInfo || '#0284C7',
      fontSize: 10,
      fontWeight: '900',
      textTransform: 'uppercase',
    },
    divider: {
      height: 1,
      backgroundColor: palette?.borderSoft || '#D6E4F0',
      opacity: 0.9,
    },
    loadingWrap: {
      minHeight: 120,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 24,
    },
    errorText: {
      color: '#B91C1C',
      fontSize: 12,
      fontWeight: '700',
      lineHeight: 16,
    },
  });

export default createStyles;
