import {StyleSheet} from 'react-native';

const createStyles = palette =>
  StyleSheet.create({
    pageRoot: {
      flex: 1,
      backgroundColor: palette?.pageBg || '#F8FAFC',
    },
    pageScroll: {
      flex: 1,
    },
    pageScrollContent: {
      paddingHorizontal: 10,
      paddingTop: 10,
      gap: 10,
    },
    topBarWrap: {
      gap: 10,
    },
    heroCard: {
      borderRadius: 16,
      borderWidth: 1,
      borderColor: palette?.borderSoft || '#D6E4F0',
      backgroundColor: palette?.cardBg || '#FFFFFF',
      padding: 14,
      gap: 10,
      shadowColor: '#0F172A',
      shadowOpacity: 0.04,
      shadowRadius: 10,
      shadowOffset: {width: 0, height: 4},
      elevation: 1,
    },
    heroHeaderRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 12,
    },
    heroTextWrap: {
      flex: 1,
      gap: 4,
    },
    heroTitle: {
      color: palette?.textPrimary || '#0F172A',
      fontSize: 18,
      fontWeight: '900',
    },
    heroSubtitle: {
      color: palette?.textSecondary || '#475569',
      fontSize: 11,
      fontWeight: '700',
      lineHeight: 15,
    },
    summaryGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    sectionCard: {
      borderRadius: 16,
      borderWidth: 1,
      borderColor: palette?.borderSoft || '#D6E4F0',
      backgroundColor: palette?.cardBg || '#FFFFFF',
      padding: 12,
      gap: 8,
    },
    sectionHeader: {
      gap: 2,
    },
    sectionTitle: {
      color: palette?.textPrimary || '#0F172A',
      fontSize: 14,
      fontWeight: '900',
    },
    sectionSubtitle: {
      color: palette?.textSecondary || '#64748B',
      fontSize: 11,
      fontWeight: '700',
      lineHeight: 14,
    },
    sectionBody: {
      gap: 8,
    },
    sectionActionRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    sectionField: {
      flexGrow: 1,
      flexBasis: 150,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: palette?.borderSoft || '#D6E4F0',
      backgroundColor: palette?.cardBgSoft || '#F8FBFF',
      padding: 10,
      gap: 3,
    },
    sectionLabel: {
      color: palette?.accentInfo || '#0284C7',
      fontSize: 10,
      fontWeight: '900',
      textTransform: 'uppercase',
      letterSpacing: 0.15,
    },
    sectionValue: {
      color: palette?.textPrimary || '#0F172A',
      fontSize: 12,
      fontWeight: '800',
      lineHeight: 15,
    },
    sectionHint: {
      color: palette?.textSecondary || '#64748B',
      fontSize: 11,
      fontWeight: '600',
      lineHeight: 14,
    },
    statusPill: {
      alignSelf: 'flex-start',
      borderRadius: 999,
      borderWidth: 1,
      borderColor: palette?.accentInfo || '#0284C7',
      backgroundColor: palette?.cardBgSoft || '#EFF8FF',
      paddingHorizontal: 10,
      paddingVertical: 4,
    },
    statusPillMuted: {
      borderColor: palette?.borderSoft || '#D6E4F0',
      backgroundColor: '#F8FAFC',
    },
    statusPillSuccess: {
      borderColor: '#16A34A',
      backgroundColor: '#F0FDF4',
    },
    statusPillDanger: {
      borderColor: '#EF4444',
      backgroundColor: '#FEF2F2',
    },
    statusPillText: {
      color: palette?.accentInfo || '#0284C7',
      fontSize: 11,
      fontWeight: '900',
      letterSpacing: 0.2,
      textTransform: 'uppercase',
    },
    statusPillTextMuted: {
      color: palette?.textSecondary || '#64748B',
    },
    statusPillTextSuccess: {
      color: '#16A34A',
    },
    statusPillTextDanger: {
      color: '#EF4444',
    },
    actionButton: {
      minHeight: 36,
      paddingHorizontal: 12,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      gap: 6,
      borderWidth: 1,
      borderColor: palette?.borderSoft || '#D6E4F0',
      backgroundColor: palette?.cardBg || '#FFFFFF',
    },
    actionButtonPrimary: {
      backgroundColor: palette?.accentInfo || '#0284C7',
      borderColor: palette?.accentInfo || '#0284C7',
    },
    actionButtonSecondary: {
      backgroundColor: palette?.cardBgSoft || '#F8FBFF',
    },
    actionButtonDisabled: {
      opacity: 0.55,
    },
    actionButtonText: {
      color: palette?.textPrimary || '#0F172A',
      fontSize: 11,
      fontWeight: '900',
      textTransform: 'uppercase',
      letterSpacing: 0.2,
    },
    actionButtonTextPrimary: {
      color: '#FFFFFF',
    },
    actionButtonTextSecondary: {
      color: palette?.accentInfo || '#0284C7',
    },
    providerChipRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    providerChip: {
      borderRadius: 999,
      borderWidth: 1,
      borderColor: palette?.borderSoft || '#D6E4F0',
      backgroundColor: palette?.cardBgSoft || '#F8FBFF',
      paddingHorizontal: 10,
      paddingVertical: 5,
    },
    providerChipText: {
      color: palette?.textSecondary || '#475569',
      fontSize: 10,
      fontWeight: '800',
      textTransform: 'uppercase',
      letterSpacing: 0.2,
    },
    routeGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    selectionPanel: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: palette?.borderSoft || '#D6E4F0',
      backgroundColor: palette?.cardBgSoft || '#F8FBFF',
      padding: 10,
      gap: 8,
    },
    selectionPanelHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 8,
    },
    selectionPanelTitleWrap: {
      flex: 1,
      gap: 2,
    },
    selectionPanelTitle: {
      color: palette?.textPrimary || '#0F172A',
      fontSize: 13,
      fontWeight: '900',
    },
    selectionPanelSubtitle: {
      color: palette?.textSecondary || '#64748B',
      fontSize: 11,
      fontWeight: '700',
      lineHeight: 14,
    },
    quoteGrid: {
      gap: 10,
    },
    quoteCard: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: palette?.borderSoft || '#D6E4F0',
      backgroundColor: palette?.cardBgSoft || '#F8FBFF',
      padding: 12,
      gap: 8,
      shadowColor: '#0F172A',
      shadowOpacity: 0.03,
      shadowRadius: 8,
      shadowOffset: {width: 0, height: 3},
      elevation: 1,
    },
    quoteCardSelected: {
      borderColor: palette?.accentInfo || '#0284C7',
      backgroundColor: '#EFF8FF',
    },
    quoteCardUnavailable: {
      opacity: 0.92,
      backgroundColor: '#F8FAFC',
    },
    quoteCardHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      gap: 10,
    },
    quoteCardTitleWrap: {
      flex: 1,
      gap: 2,
    },
    quoteCardTitle: {
      color: palette?.textPrimary || '#0F172A',
      fontSize: 14,
      fontWeight: '900',
    },
    quoteCardMeta: {
      color: palette?.textSecondary || '#64748B',
      fontSize: 10,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.15,
    },
    quoteCardBody: {
      gap: 4,
    },
    quotePrice: {
      color: palette?.textPrimary || '#0F172A',
      fontSize: 18,
      fontWeight: '900',
    },
    quoteEta: {
      color: palette?.textSecondary || '#64748B',
      fontSize: 11,
      fontWeight: '700',
    },
    quoteSummary: {
      color: palette?.accentInfo || '#0284C7',
      fontSize: 11,
      fontWeight: '800',
      textTransform: 'uppercase',
      letterSpacing: 0.15,
    },
    quoteMessage: {
      color: palette?.textSecondary || '#475569',
      fontSize: 11,
      fontWeight: '600',
      lineHeight: 14,
    },
    quoteFooter: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    emptyState: {
      borderRadius: 14,
      borderWidth: 1,
      borderStyle: 'dashed',
      borderColor: palette?.borderSoft || '#D6E4F0',
      backgroundColor: palette?.cardBg || '#FFFFFF',
      padding: 12,
      gap: 6,
    },
    emptyStateTitle: {
      color: palette?.textPrimary || '#0F172A',
      fontSize: 12,
      fontWeight: '900',
    },
    emptyStateText: {
      color: palette?.textSecondary || '#64748B',
      fontSize: 11,
      fontWeight: '600',
      lineHeight: 14,
    },
    loadingWrap: {
      minHeight: 120,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 24,
    },
    errorBanner: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: '#FECACA',
      backgroundColor: '#FEF2F2',
      padding: 10,
    },
    errorText: {
      color: '#B91C1C',
      fontSize: 12,
      fontWeight: '700',
      lineHeight: 16,
    },
  });

export default createStyles;
