import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  scrollContent: {
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 20,
    gap: 12,
  },
  loadingContainer: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  errorCard: {
    backgroundColor: '#FEF2F2',
    borderColor: '#FCA5A5',
    borderRadius: 18,
    borderWidth: 1,
    gap: 8,
    padding: 16,
  },
  errorTitle: {
    color: '#991B1B',
    fontSize: 15,
    fontWeight: '800',
  },
  errorText: {
    color: '#B91C1C',
    fontSize: 13,
    lineHeight: 18,
  },
  heroCard: {
    backgroundColor: '#0F172A',
    borderRadius: 22,
    gap: 14,
    overflow: 'hidden',
    padding: 18,
  },
  heroEyebrow: {
    color: '#7DD3FC',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  heroTitle: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: '900',
    lineHeight: 28,
  },
  heroText: {
    color: '#CBD5E1',
    fontSize: 13,
    lineHeight: 19,
  },
  heroPillRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  heroPill: {
    borderColor: '#334155',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  heroPillText: {
    color: '#E2E8F0',
    fontSize: 12,
    fontWeight: '700',
  },
  sectionCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E2E8F0',
    borderRadius: 20,
    borderWidth: 1,
    gap: 14,
    padding: 16,
  },
  sectionHeader: {
    gap: 6,
  },
  sectionTitle: {
    color: '#0F172A',
    fontSize: 18,
    fontWeight: '900',
  },
  sectionText: {
    color: '#475569',
    fontSize: 13,
    lineHeight: 19,
  },
  sectionNote: {
    color: '#64748B',
    fontSize: 12,
    lineHeight: 17,
  },
  fieldGroup: {
    gap: 10,
  },
  fieldLabel: {
    color: '#334155',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  textInput: {
    backgroundColor: '#FFFFFF',
    borderColor: '#CBD5E1',
    borderRadius: 14,
    borderWidth: 1,
    color: '#0F172A',
    fontSize: 15,
    minHeight: 48,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  textInputMuted: {
    color: '#64748B',
  },
  segmentedRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  segmentedOption: {
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderColor: '#CBD5E1',
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 48,
    minWidth: 120,
    paddingHorizontal: 14,
  },
  segmentedOptionActive: {
    backgroundColor: '#0EA5E9',
    borderColor: '#0284C7',
  },
  segmentedLabel: {
    color: '#0F172A',
    fontSize: 14,
    fontWeight: '800',
  },
  segmentedLabelActive: {
    color: '#FFFFFF',
  },
  bandCard: {
    backgroundColor: '#F8FAFC',
    borderColor: '#E2E8F0',
    borderRadius: 18,
    borderWidth: 1,
    gap: 12,
    padding: 14,
  },
  bandHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  bandTitleWrap: {
    flex: 1,
    gap: 4,
  },
  bandIndex: {
    color: '#0F172A',
    fontSize: 14,
    fontWeight: '900',
  },
  bandSubtitle: {
    color: '#64748B',
    fontSize: 12,
    lineHeight: 17,
  },
  bandRemoveButton: {
    alignItems: 'center',
    backgroundColor: '#FFF1F2',
    borderRadius: 999,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  bandGrid: {
    gap: 10,
  },
  bandGridRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  bandField: {
    flexGrow: 1,
    flexBasis: '48%',
    gap: 6,
    minWidth: 140,
  },
  bandFieldFull: {
    flexBasis: '100%',
  },
  bandFieldInput: {
    minHeight: 46,
  },
  buttonRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#0EA5E9',
    borderRadius: 16,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 18,
  },
  primaryButtonDisabled: {
    opacity: 0.6,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: '#E2E8F0',
    borderRadius: 16,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 18,
  },
  secondaryButtonText: {
    color: '#0F172A',
    fontSize: 14,
    fontWeight: '800',
  },
  ghostButton: {
    alignItems: 'center',
    borderColor: '#CBD5E1',
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 46,
    paddingHorizontal: 16,
  },
  ghostButtonText: {
    color: '#0F172A',
    fontSize: 13,
    fontWeight: '800',
  },
  actionBar: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  helperText: {
    color: '#64748B',
    fontSize: 12,
    lineHeight: 17,
  },
  emptyState: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#E2E8F0',
    borderRadius: 20,
    borderWidth: 1,
    gap: 8,
    padding: 18,
  },
  emptyStateTitle: {
    color: '#0F172A',
    fontSize: 16,
    fontWeight: '900',
    textAlign: 'center',
  },
  emptyStateText: {
    color: '#64748B',
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
  },
  tableWrap: {
    minHeight: 320,
  },
  listCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E2E8F0',
    borderRadius: 18,
    borderWidth: 1,
    gap: 12,
    padding: 16,
  },
  companyRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    paddingVertical: 8,
  },
  companyIdentity: {
    flex: 1,
    gap: 4,
  },
  companyTitle: {
    color: '#0F172A',
    fontSize: 15,
    fontWeight: '800',
  },
  companyMeta: {
    color: '#64748B',
    fontSize: 12,
    lineHeight: 17,
  },
  statusBadge: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  statusBadgeActive: {
    backgroundColor: '#DCFCE7',
  },
  statusBadgeInactive: {
    backgroundColor: '#FEF3C7',
  },
  statusBadgeText: {
    color: '#0F172A',
    fontSize: 11,
    fontWeight: '800',
  },
  toggleColumn: {
    alignItems: 'flex-end',
    gap: 4,
  },
  sectionDivider: {
    backgroundColor: '#E2E8F0',
    height: 1,
    width: '100%',
  },
});

export default styles;
